version: '3'
services:
  movies-api-mongo:
    image: mongo:5
    volumes:
    - ./mongo-seed:/docker-entrypoint-initdb.d
    ports:
    - 127.0.0.1:27017:27017/tcp

  datadog-agent:
    image: datadog/agent:latest
    environment:
      DD_API_KEY: ${DD_API_KEY}
      DD_REMOTE_CONFIGURATION_ENABLED: 'true'
      DD_APM_ENABLED: 'true'
      DD_SITE: 'datadoghq.com'
      DD_APM_NON_LOCAL_TRAFFIC: 'true'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
    expose:
      - "8126"

  leaky-api-java:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8082:8082
    environment:
      DD_AGENT_HOST: "datadog-agent"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/"]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      - datadog-agent
    restart: always
