version: '3'
services:
  movies-api-mongo:
    image: mongo:5
    volumes:
    - ./mongo-seed:/docker-entrypoint-initdb.d
    ports:
    - 127.0.0.1:27017:27017/tcp

  leaky-api-java:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8082:8082
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/"]
      interval: 10s
      timeout: 5s
      retries: 3
